fix: adds oomphinc to allow-plugins
fourkitchens/sous-drupal-project pull request #70
Opened 2022-08-03 21:59 UTC by cbfannin

### Purpose:
To include oomphinc to the allow-plugins tree in composer.json.

### Testing:
Create the project as you normally would with `composer create-project`. You should no longer see the following:
```
oomphinc/composer-installers-extender contains a Composer plugin which is b  
 locked by your allow-plugins config. You may add it to the list if you cons  
 ider it safe.                                 
 You can run "composer config --no-plugins allow-plugins.oomphinc/composer-i  
 nstallers-extender [true|false]" to enable it (true) or disable it explicit  
 ly and suppress this exception (false)                    
 See https://getcomposer.org/allow-plugins
```

2022-08-04 14:33 UTC, generalredneck commented
Got this email last night:
```
From: 'Packagist.org' via Bender <bender@fourkitchens.com>
Date: Wed, Aug 3, 2022 at 4:52 PM
Subject: fourkitchens/sous-drupal-project failed to update, invalid composer.json data
To: fourkitchens <bender@fourkitchens.com>, americkson <adam@fourkitchens.com>


The fourkitchens/sous-drupal-project package of which you are a maintainer has
failed to update due to invalid data contained in your composer.json.
Please address this as soon as possible since the package stopped updating.

It is recommended that you use `composer validate` to check for errors when you
change your composer.json.

Below is the update log which should highlight errors as
"Skipped branch ...":

[Composer\Repository\InvalidRepositoryException]: Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

Skipped branch fix-oomphinc-allow-plugins, "d5af40a072a541412bf68f6ae99cf48333b7c707:composer.json" does not contain valid JSON
Parse error on line 46:
...": true            "oomphinc/composer-i...
---------------------^
Expected one of: 'EOF', '}', ',', ']'
```

2022-08-04 14:35 UTC, generalredneck requested changes

2022-08-04 14:35 UTC, generalredneck commented on composer.json
>              "zaporylie/composer-drupal-optimizations": true
You are missing a comma,
Give this a `composer install` in the future before submitting the pr when you make a change. 

Check out the feedback on the CI also if you get the chance.
https://app.circleci.com/pipelines/github/fourkitchens/sous-drupal-project/239/workflows/2f124e0b-a18d-4705-8dfa-2b3d5009e2de/jobs/407?invite=true#step-103-4

2022-08-17 12:30 UTC, cbfannin reviewed
How do I get past this msg? "Merging is blocked
Merging can be performed automatically once the requested changes are addressed."

2022-08-24 12:50 UTC, generalredneck approved these changes

2022-08-24 12:50 UTC, merged

2022-08-24 12:53 UTC, fkbender commented
:tada: This PR is included in version 4.1.3 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-project/releases/tag/4.1.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: