3325719 - Create a custom admin theme and custom module
fourkitchens/sous-drupal-project pull request #82
Opened 2023-02-08 21:37 UTC by JRuiz28

## Ticket
[Issue](https://www.drupal.org/project/sous/issues/3325719)

## Testing:

- [ ] Copy & paste the folder themes & modules in folder: `web`
- [ ] Run `composer install && lando rebuild`.
- [ ] Go to `` and validate custom theme be there.

2023-03-01 22:54 UTC, ccjjmartin requested changes
@JRuiz28 Composer is setup to install everything in the `web` directory so these will need to be in there and we will need to make sure that we have composer setup to persist these directories upon install.  The names of the module and theme I think needs some adjustment, how about:

`sous` for the module name
`sous_admin` for the theme name

2023-03-02 19:57 UTC, JRuiz28 commented
The changes have been added.
Thank you so much @ccjjmartin for your advice.

Just two details:
1. The site doesn't seem to recognize the module if it's called just `sous`, so it's called `sous_custom`.
2. The name for the `sous_admin` theme is apparently already used in the _distro_ and it makes the site not work correctly, so it is also called `sous_custom`.

2023-03-06 23:04 UTC, ccjjmartin commented
@JRuiz28 I am not sure if we need to preserve these paths so composer doesn't wipe them out, so I asked the question here in Slack: https://fourkitchens.slack.com/archives/C07506UNQ/p1678143813991309

2023-03-06 23:05 UTC, ccjjmartin commented
Preserve paths: https://github.com/drupal-composer/preserve-paths#example

2023-03-08 16:24 UTC, rigoucr commented
hi @ccjjmartin and @JRuiz28 quick question? What about moving this code to independent repos ?  I mean , creating a repo for the `sous_admin_extras`  module and other for the `sous_admin` theme, Advantages of this approach : we are think about of get rid of the Distro and move to drupal templates, so moving this into different repos giving us the chances to only have to pull from Pckagist or drupal.org this packages

2023-03-08 19:12 UTC, JRuiz28 commented
Composer preserve paths added! 👍🏾

2023-03-10 19:09 UTC, JRuiz28 commented
Work well for me! 👍🏾

2023-07-31 01:27 UTC, cbfannin commented
@ccjjmartin I was doing some triaging of our issues marked Needs Review on d.o Where did we end up with this issue?

2023-08-09 21:04 UTC, laura-johnson commented
Since this PR was created we have pulled out the distro. We need to make sure it doesn't pull the distro back in, and update the module to D9, and leave out most of the composer.json changes.

2025-03-15 14:50 UTC, closed without merging