Remove profile
fourkitchens/sous-drupal-project pull request #87
Opened 2023-03-01 22:25 UTC by ccjjmartin

2023-04-12 16:16 UTC, callinmullaney requested changes
@ccjjmartin See my nvm code comment. Also, while I am able to build a local project successfully with this branch I believe the `uuid` and 
```_core:
  default_config_hash:
```
stuff should be removed from the config files. These are added to the config after the first export post-install and should be unique per-site.

2023-04-12 20:47 UTC, ccjjmartin commented on .nvmrc
> +16.13
@callinmullaney Reverted

2023-04-12 20:48 UTC, ccjjmartin commented
@callinmullaney As discussed the core key shouldn't be in issue anymore so I think we can leave it.  This should be ready for you to pull into your branch.

2023-04-21 18:47 UTC, callinmullaney approved these changes
This has been a long road @ccjjmartin but I think we made it. :shipit:

2023-04-21 18:50 UTC, merged

2023-04-21 18:53 UTC, fkbender commented
:tada: This PR is included in version 4.4.0 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-project/releases/tag/4.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: